### ISSUE TITLE
ApMC seems to crash when count of formula is less than threshold

### ISSUE THREAD

**Issue by allrtaken** [meelgroup/approxmc#15]
Hi,

I was running ApMC on some formulas where the solution count was less than threshold (or even UNSAT). In such cases, it seems that ApMC crashes with a failed assertion. I have attached a sample file and the output I get.

Thanks!
[apmc_failed_op.txt](https://github.com/meelgroup/approxmc/files/5215325/apmc_failed_op.txt)
[test_10_1_0.cnf.txt](https://github.com/meelgroup/approxmc/files/5215329/test_10_1_0.cnf.txt)

**Comment by msoos** [comment]
Wow, amazing find! This is a bug that was introduced sometime due to incorrect start iteration. It doesn't affect results luckily, only made this edge case fail. I am closing with the fix commit in a sec. Thanks again, great find! Let us know if you find anything else!
