### ISSUE TITLE
Is there any way to see the solutions in the bounded solution count ?

### ISSUE THREAD

**Issue by sagarAI** [meelgroup/approxmc#23]
Hi I am running the approxmc for some very simple CNF's I would like to save the solutions from the last set of cells ? Is it somehow possible ?

**Comment by msoos** [comment]
Hi,

It is possible, but it doesn't help much in terms of sampling. Instead, I suggest you use our sampler, here:

https://github.com/meelgroup/unigen

That will give you example solutions and will also tell you the approximate number of solutions :) All in one! It uses ApproxMC as a subsystem.

Cheers,

Mate
