### ISSUE TITLE
What value does --sparse option take?

### ISSUE THREAD

**Issue by hflsmax** [meelgroup/approxmc#24]
The sparse option is not very well documented. What value should I provide to this option?

**Comment by msoos** [comment]
Hi

Thanks for reaching out! I agree it's unfortunately not very well-documented. I suggest leaving it at the default value, `0`. However, if you have time, you can experiment with `1`. It does not accept any other value than 1/0. I have now added a commit to improve the documentation in the `--help`: commit  207663d867c76dd3f9de5634d19032ba057f9941.

The `--sparse` flag should should work better with `1` in case you have a *very* large projection set (say, over 200 variables) and you expect to have a lot of solutions (say, over 2^100) . But again, I suggest trying with `0` first, it's the default and should work well in most cases. If your projection set is very large, I suggest trying to minimize it. Think about the problem you are trying to solve. With very large projection sets, or without a projection set given (with `c ind .... 0`) ApproxMC may run extremely slowly.

I hope the above helped. Let us know if we can help you with using the tool. We also have a newer version that in case you struggle with the current one, we can give you a static binary of. Let us know if you run into issues, we can maybe help :)

Cheers and good luck,

Mate

**Comment by msoos** [comment]
(Closing the issue because the above should fix it. However, please open a new issue for questions/comments/etc! We are happy to hear what you have to say!)
