### ISSUE TITLE
ApproxMC ignores SIGINT

### ISSUE THREAD

**Issue by yxliang01** [meelgroup/ApproxMC#3]
Hello @kuldeepmeel and @msoos ,

It appears that ApproxMC ignores SIGINT which makes it hard to be stopped without sending SIGKILL to the process. I think it might be a good idea to be able to either stop when receiving SIGINT or supports timeout as a switch?

Thanks
Xiao Liang

**Comment by msoos** [comment]
For me, SIGINT is not being ignored -- are you running under Docker? Or what is your setup? For me, SIGINT works just fine and aborts the process :) Also, I looked at all source code and SIGINT is not being caught by any system other than the "main.cpp" code of CryptoMiniSat which is 100% surely not being called, it's not even being compiled in my setup :) So I suspect it's either you are sending the SIGINT to the wrong process or it's Docker and that's what's confusing. 

Please see: https://stackoverflow.com/questions/25687131/how-to-send-signal-to-program-run-in-a-docker-container

and use the syntax:

```
docker kill --signal="<signal>" <container name or id>
```

Let me know if this worked. Thanks!

**Comment by msoos** [comment]
(also, as a future reference, it's not polite to "@" people in GitHub, we are the maintainers and get an email immediately of course, without the "@" :) )

**Comment by yxliang01** [comment]
Thanks for your comment. I am running in docker container. I have tried `docker kill --signal=sigint APPROXMC_CONTAINER_ID` for three different instances. But, it doesn't seem effective..

**Comment by msoos** [comment]
Sorry, but I cannot help. This is an issue with Docker and/or your system and has nothing to do with ApproxMC. Please look around Docker documentation to find and fix the issue. It has nothing to do with ApproxMC. Good luck!
