### ISSUE TITLE
python interface shows ImportError 

### ISSUE THREAD

**Issue by yizza91** [meelgroup/approxmc#34]
I use python 3.10 version on my machine with ubuntu 22. I installed normally the package but when I try to use it, I got the following error:
from pyapproxmc import Counter
ImportError: /home/xxxx/.local/lib/python3.10/site-packages/pyapproxmc.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTIN5boost7archive6detail14basic_iarchiveE

I've tried other version of python (3.8), and I still get the same error on Linux machine

**Comment by msoos** [comment]
Hi,

Thank you, yes, this is currently a known issue but is being fixed as we speak, should be fixed in about 48h. Sorry, it takes a while for all the python packages to build and it's the weekend. 

Mate

**Comment by msoos** [comment]
Hi! Can you please check to see if it's been fixed? I believe I have managed to fix it but it'd be great if you could check!

Thank you so much,

Mate

**Comment by yizza91** [comment]
I installed the new version 4.1.13 and it works now on Linux.  Thanks

**Comment by msoos** [comment]
Great to hear :)

Cheers,

Mate

**Comment by yizza91** [comment]
BTW, how to deactivate the printed message: 
c WARNING: Turning off gates, because the sampling size is small, so we can just do it

This was not shown in the previous version

**Comment by msoos** [comment]
Ooooops, nice catch! Thanks, I just fixed it, the newer version will have this fixed. Sorry about that :(

Maste
