### ISSUE TITLE
The flag for exact count  -- imprecise question, cannot answer

### ISSUE THREAD

**Issue by zzwonder** [meelgroup/approxmc#51]
Thanks for the contribution. I am wondering if ApproxMC still provides the exact-count-flag when the output is an exact model count. Thank you!

**Comment by msoos** [comment]
Hi,

I don't understand your question. Can you please re-phrase it? I could try to guess what you are asking, but none of your sentences seem to be precise enough for me to guess correctly.  Looking forward to an update that has at least one sentence with a question mark in it, and an example of what you'd like to see. Cheers,

Mate

**Comment by zzwonder** [comment]
Hi Mate,

Thanks for your timely reply! Sorry for the confusion. I am trying to use [Deweight](https://github.com/meelgroup/deweight/tree/main), which uses ApproxMC as the underlining model counter. The [Python wrapper of Deweight](https://github.com/meelgroup/deweight/blob/f80235955ba4e9a86afb4388c94e7e474ce0ad8f/deweight_wrapper.py#L66C19-L66C42) captures the output of ApproxMC with the form "i.e. we got exact count". When this line of output of ApproxMC is captured, Deweight knows that ApproxMC produces an exact model count. Otherwise, we know that ApproxMC provides an approximate model count. Nevertheless, I can not find a line in ApproxMC that produces such outputs in the current version. Does ApproxMC still provide a flag for giving an exact model count in the output?

Thanks,
Zhiwei

**Comment by msoos** [comment]
Thanks, I now understand it. I wouldn't call it a flag but OK. Next time, please ALWAYS give an example. You didn't give an example, even on your second try. Learning how to write good issues/bug reports is an important skill. It's worth learning it.

I will release a new ApproxMC soon. For the moment, here's a static binary that prints that when it finds an exact solution:

[approxmc.gz](https://github.com/meelgroup/approxmc/files/14908573/approxmc.gz)

Good luck,

Mate
