### ISSUE TITLE
Installing on Mac

### ISSUE THREAD

**Issue by edredre** [meelgroup/ApproxMC#7]
Hi, is there any chance to install ApproxMC (v3) on my Mac? I already have cryptominisat installed and tried to perform the steps needed for Linux, but the "make" command failed, reporting the following message:

```
=========
[ 25%] Building CXX object approxmc-src/CMakeFiles/approxmc.dir/approxmc.cpp.o
/Users/Daniele/Desktop/MyComputer/MieiArticoli/model counting/python/Python/approxmc/src/approxmc.cpp:470:21: error: 
      no member named 'get_text_version_info' in 'CMSat::SATSolver'
    cout << solver->get_text_version_info();
            ~~~~~~  ^
1 error generated.
make[2]: *** [approxmc-src/CMakeFiles/approxmc.dir/approxmc.cpp.o] Error 1
make[1]: *** [approxmc-src/CMakeFiles/approxmc.dir/all] Error 2
make: *** [all] Error 2
=========
```

Is it a Mac related problem or do I need to perform some other step?
Thanks

Dan

**Comment by msoos** [comment]
Hi,

You are using an outdated CryptoMiniSat. Please re-clone both ApproxMC and CryptoMiniSat and then build again. It should then work. This has nothing to do with Mac, it simply is an issue that your CryptoMiniSat is too old. Please delete your current CryptoMiniSat installation, and follow the steps in the README. In case you still run into problems, please open a new issue, we will be happy to debug and fix. It is very important for us that the system builds and runs on Mac! I would be **very** happy if you could confirm it works after re-cloning and re-building :)

Thanks again,

Mate

**Comment by edredre** [comment]
Yes Mate, it perfectly works!
Thanks!

**Comment by msoos** [comment]
Glad to hear! Let us know if you bump into any issues :)

Mate
