### ISSUE TITLE
Setting parameters epsilon and delta

### ISSUE THREAD

**Issue by edredre** [meelgroup/ApproxMC#8]
Hi, is there any possibility of setting the values of parameters epsilon and delta? In you paper, you write that they are set to 0.8 and 0.1, respectively... Are they built in the code or can be passed as parameters (in the --help this option does not appear). Thanks!

**Comment by msoos** [comment]
Hey,

Pleat pass the "--help" option. It should display these options. If not,
please let us know! We are happy to fix.

Cheers,

Mate

**Comment by edredre** [comment]
this is my display (upon calling approxmc --help):

Approximate counter
appmc [options] inputfile


AppMC options:
  -h [ --help ]           Prints help
  --version               Print version info
  --input arg             file(s) to read
  -v [ --verb ] arg (=1)  verbosity
  -s [ --seed ] arg (=1)  Seed
  --threshold arg (=72)   Number of solutions to check for -- used to be 
                          'pivotAC'
  --measure arg (=9)      Number of measurements -- used to be 'samplingT' or 
                          'tApproxMC'
  --start arg (=0)        Start at this many XORs
  --log arg               Log of ApproxMC iterations.
  --th arg (=1)           How many solving threads to use per solver call
  --vcl arg (=0)          Print banning clause + xor clauses. Highly verbose.
  --sparse arg (=0)       Generate sparse XORs when possible
  --kappa arg (=0.638)    Uniformity parameter (see TACAS-15 paper)
  --startiter arg (=0)    If positive, use instead of startiter computed by 
                          AppMC

**Comment by msoos** [comment]
Hi,

Yes, those are the ones you are looking for! Please see kappa and @Kuldeep
should be able to answer which is the other one you mean. The system
computes some of these values based on other values you provide.

Kuldeep will answer that question here or you can look into the code and
find the calculation and associated parameters.

Mate

**Comment by kuldeepmeel** [comment]
Hi:
   Thanks for pointing this out. We have now provided a better interface to the options. You should be able to edit epsilon and delta directly from command line. 

Many thanks for reporting this -- look forward to learning of your experience. 
Kuldeep
